title: Russell Paredes 
description: A portfolio containing an assortment of Russell's Projects
theme: just-the-docs

url: https://Tsurei.github.io/Portfolio

aux_links:
  Linkedin: https://www.linkedin.com/in/russell-paredes-5b6348232
  Repository: https://github.com/Tsurei/Portfolio
