title: Russell Paredes 
description: A portfolio containing an assortment of Russell's Projects
theme: just-the-docs

url: https://Tsurei.github.io/Portfolio

aux_links:
  Template Repository: https://github.com/Tsurei/Portfolio
